### ISSUE TITLE
Question on how to categorize

### ISSUE THREAD

**Issue by xxradar** [OWASP/www-project-top-10-ci-cd-security-risks#11]
Hi, 
btw, very great work.

Q I have is, where would you categorize an attack where env variables are overwritten in between pipelines.

1. pipeline1 sets / pass malicious $CIJOB to pipeline2 $CIJOB where it is unvalidated (ex. code injection accross pipelines or different ci/cd systems)

2. an unforseen env. variable is overwritten bij the api call triggering the pipeline (ex. $CIJOB) 

In both cases, it boils down to insecure pipeline code.

Kind regards,

**Comment by omer-cider** [comment]
Hi,

As far as I can see, these use cases don't fit any of the Top 10 risks. It makes since to me, as I don't think they're very common. I'd categorize it as _Input Validation_.
