### ISSUE TITLE
Possible missing attack vector in CICD-SEC-3: Dependency Chain Abuse

### ISSUE THREAD

**Issue by ChristopherHackett** [OWASP/www-project-top-10-ci-cd-security-risks#5]
The recent [HN post about a malicious dependency](https://news.ycombinator.com/item?id=33729514) I thought about this project again. 

I don't know enough about this specific case but the situation is a little odd and gives me rise to think of another significant vector of dependency chain abuse: Malicious actor authoring useful dependency with the purpose of shipping a backdoor. 

The linked situation may not be an example of this however it is worth considering incorporating the vector as it feels a departure from those listed.

**Comment by omer-cider** [comment]
Hi @ChristopherHackett, to make sure what use case you refer to - is that where a malicious actor compromises a maintainer account and introduces malicious code in the package? That's what I understood from your description, and if that's the case, CICD-SEC-3 covers it:

> Dependency hijacking - Obtaining control of the account of a package maintainer on the public repository, in order to upload a new, malicious version of a widely used package, with the intent of compromising unsuspecting clients who pull the latest version of the package.
